import { formatCurrency } from "@/lib/utils";
import type { AnalyticsSnapshot } from "../types";

function Kpi({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums text-slate-900">{value}</p></div>; }

export function AnalyticsView({ snapshot }: { snapshot: AnalyticsSnapshot }) {
  const debtors = snapshot.balances.filter((entry) => entry.state === "DEUDA");
  return <div className="space-y-8"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Kpi label="Ingresos hoy" value={formatCurrency(snapshot.revenueToday)} /><Kpi label="Ingresos del mes" value={formatCurrency(snapshot.revenueMonth)} /><Kpi label="Gastos hoy" value={formatCurrency(snapshot.expensesToday)} /><Kpi label="Gastos del mes" value={formatCurrency(snapshot.expensesMonth)} /><Kpi label="Alquileres semana" value={String(snapshot.weeklyRentals)} /></div><div className="grid gap-6 lg:grid-cols-3"><section className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="font-semibold text-slate-900">Saldos</h2><div className="mt-4 space-y-2">{snapshot.balances.map(({ player, state }) => <div key={player.id} className="flex items-center justify-between border-b border-slate-100 py-2 text-sm"><span>{player.first_name} {player.last_name}</span><span className={state === "DEUDA" ? "font-mono text-red-700" : state === "A_FAVOR" ? "font-mono text-emerald-700" : "font-mono text-slate-500"}>{formatCurrency(player.current_balance)}</span></div>)}{snapshot.balances.length === 0 && <p className="text-sm text-slate-500">No hay saldos para mostrar.</p>}</div></section><section className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="font-semibold text-slate-900">Ranking semanal</h2><p className="mt-1 text-xs text-slate-500">Sólo jugadores con más de 2 alquileres.</p><div className="mt-4 space-y-2">{snapshot.weeklyRanking.map((entry, index) => <div key={entry.playerId} className="flex justify-between border-b border-slate-100 py-2 text-sm"><span>{index + 1}. {entry.playerName}</span><strong>{entry.rentals}</strong></div>)}{snapshot.weeklyRanking.length === 0 && <p className="text-sm text-slate-500">Todavía no hay jugadores en el ranking.</p>}</div></section><section className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="font-semibold text-slate-900">Ranking mensual</h2><p className="mt-1 text-xs text-slate-500">Sólo jugadores con más de 8 alquileres.</p><div className="mt-4 space-y-2">{snapshot.monthlyRanking.map((entry, index) => <div key={entry.playerId} className="flex justify-between border-b border-slate-100 py-2 text-sm"><span>{index + 1}. {entry.playerName}</span><strong>{entry.rentals}</strong></div>)}{snapshot.monthlyRanking.length === 0 && <p className="text-sm text-slate-500">Todavía no hay jugadores en el ranking.</p>}</div></section></div><p className="text-sm text-slate-500">{debtors.length} jugador{debtors.length === 1 ? "" : "es"} con deuda pendiente.</p></div>;
}
