import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { PageContainer } from "@/components/layout/page-container";
import { getInventoryProducts, getStockMovements } from "@/features/products/queries";
import { StockAdjustForm } from "@/features/products/components/stock-adjust-form";
import { StockMovementTable } from "@/features/products/components/stock-movement-table";

export default async function StockPage() {
  const [products, movements] = await Promise.all([getInventoryProducts(), getStockMovements()]);
  return <PageContainer><div className="mb-8"><p className="text-sm font-medium uppercase tracking-[0.2em] text-emerald-700">Control trazable</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-900">Stock</h1><p className="mt-2 text-slate-500">Los ajustes aceptan valores negativos y dejan un movimiento inmutable.</p></div><Card className="mb-6"><CardHeader><h2 className="text-lg font-semibold text-slate-900">Ajustar stock</h2></CardHeader><CardContent><StockAdjustForm products={products} /></CardContent></Card><Card className="mb-6"><CardHeader><h2 className="text-lg font-semibold text-slate-900">Existencias actuales</h2></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[560px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Producto</th><th className="px-5 py-3">Estado</th><th className="px-5 py-3 text-right">Stock</th></tr></thead><tbody className="divide-y divide-slate-100">{products.map((product) => <tr key={product.id}><td className="px-5 py-4 font-medium text-slate-900">{product.name}</td><td className="px-5 py-4">{!product.is_active ? <span className="text-slate-400">Inactivo</span> : product.is_court_rental ? <span className="text-emerald-700">Alquiler, sin stock físico</span> : product.current_stock < 0 ? <span className="font-semibold text-red-700">Stock negativo</span> : product.current_stock <= 5 ? <span className="text-amber-700">Stock bajo</span> : <span className="text-slate-600">Normal</span>}</td><td className="px-5 py-4 text-right font-mono font-semibold tabular-nums">{product.is_court_rental ? "-" : product.current_stock}</td></tr>)}</tbody></table></CardContent></Card><Card><CardHeader><h2 className="text-lg font-semibold text-slate-900">Historial de movimientos</h2></CardHeader><CardContent className="p-0"><StockMovementTable movements={movements} products={products} /></CardContent></Card></PageContainer>;
}