import Link from "next/link";
import { ArrowUpRight, CalendarDays, CircleDollarSign, ShoppingCart, Users } from "lucide-react";
import { PageContainer } from "@/components/layout/page-container";
import { getAnalyticsSnapshot } from "@/features/reports/queries";
import { formatCurrency } from "@/lib/utils";

export default async function DashboardPage() {
  const snapshot = await getAnalyticsSnapshot();
  const metrics = [{ label: "Ingresos de hoy", value: formatCurrency(snapshot.revenueToday), icon: CircleDollarSign }, { label: "Ingresos del mes", value: formatCurrency(snapshot.revenueMonth), icon: CircleDollarSign }, { label: "Gastos del mes", value: formatCurrency(snapshot.expensesMonth), icon: ShoppingCart }, { label: "Alquileres esta semana", value: String(snapshot.weeklyRentals), icon: CalendarDays }];
  const balancesWithDebt = snapshot.balances.filter((entry) => entry.state === "DEUDA");
  return <PageContainer><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-emerald-700">Resumen</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-900">Inicio</h1><p className="mt-2 text-slate-500">Estado actualizado desde ventas, compras y cuentas corrientes.</p></div><Link href="/ventas" className="inline-flex items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 py-3 text-sm font-semibold text-white transition hover:bg-emerald-700">Registrar operación <ArrowUpRight size={17} aria-hidden="true" /></Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({ label, value, icon: Icon }) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><Icon className="text-emerald-600" size={20} aria-hidden="true" /><p className="mt-6 text-xs font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums text-slate-900">{value}</p></div>)}</div><section className="mt-8 grid gap-6 lg:grid-cols-[1.3fr_1fr]"><div className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-3"><Users className="text-emerald-600" size={20} aria-hidden="true" /><h2 className="font-semibold text-slate-800">Situación de cuentas corrientes</h2></div>{balancesWithDebt.length === 0 ? <p className="mt-8 text-sm text-slate-500">No hay jugadores con deuda pendiente.</p> : <div className="mt-5 space-y-2">{balancesWithDebt.slice(0, 5).map(({ player }) => <div key={player.id} className="flex justify-between border-b border-slate-100 py-2 text-sm"><span>{player.first_name} {player.last_name}</span><span className="font-mono tabular-nums text-red-700">{formatCurrency(player.current_balance)}</span></div>)}</div>}</div><div className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="font-semibold text-slate-800">Últimas operaciones</h2><div className="mt-5 space-y-3">{snapshot.recentSales.map((sale) => <div key={sale.id} className="flex justify-between gap-3 border-b border-slate-100 pb-3 text-sm"><span>{sale.items[0]?.product?.name ?? "Venta"}</span><span className="font-mono tabular-nums">{formatCurrency(sale.total_amount)}</span></div>)}{snapshot.recentSales.length === 0 && <p className="text-sm text-slate-500">Las operaciones recientes aparecerán aquí.</p>}</div></div></section></PageContainer>;
}